USE SCOTT;


SELECT ENAME,SAL,DNAME
FROM EMP NATURAL JOIN DEPT
WHERE DEPTNO = '20' AND SAL > '1800';


SELECT ENAME,DEPTNO,DNAME,LOC
FROM EMP NATURAL JOIN DEPT
WHERE SAL >2000 AND LOC = 'NEW YORK';

SELECT ENAME ,LOC
FROM EMP ,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT DNAME, SAL
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DNAME = 'ACCOUNTING';



SELECT DNAME,SAL*12
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL > 2340; 



SELECT ENAME,DNAME
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.ENAME LIKE "A%";


SELECT ENAME,DNAME
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND JOB = 'SALESMAN';




SELECT DNAME ,JOB 
FROM EMP,DEPT
WHERE DEPT.DEPTNO = EMP.DEPTNO AND JOB LIKE 'S%' AND DNAME LIKE 'S%';


SELECT DNAME ,MGR
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND MGR = '7839';

SELECT DNAME,HIREDATE
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND HIREDATE >'1983-12-31'
AND (DNAME = 'ACCOUNTS' OR DNAME = 'RESEARCH');




SELECT DNAME, HIREDATE
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
  AND HIREDATE > '1983-12-31' 
  AND (DNAME = 'ACCOUNTS' OR DNAME = 'RESEARCH');

SELECT ENAME,DNAME
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO 
AND COMM IS NOT NULL
AND (EMP.DEPTNO = 10 OR EMP.DEPTNO = 20); 




SELECT *
FROM EMP;